#ifndef CONSTANTES_HPP
#define CONSTANTES_HPP

#define NOMEJANELAORIGINAL "ORIGINAL IMAGE" /* Constantes dos nomes das janelas. */
#define NOMEJANELANOVA "NEW IMAGE"
#define NOMEINTERFACE "USER INTERFACE"
#define NOMEHISTOGRAMA "HISTOGRAM"
#define JANELA_ANTESEQUAL "BEFORE EQUALIZATION"
#define JANELA_HISTORIGINAL "ORIGINAL HISTOGRAM"
#define JANELA_DEPOISEQUAL "AFTER EQUALIZATION"
#define JANELA_HISTEQUALIZADO "EQUALIZED HISTOGRAM"

#define DIMENSAORGB 3
#define DIMENSAOKERNEL 9
#define INTENSIDADESIMAGEM 256
#define NORMALIZACAOHISTOGRAMA 300
#define LARGURABARRAS 4
#define TAMANHOFONTE 0.55
#define ESC 27
#define R 2
#define G 1
#define B 0

#define LARGURABOTAO 150		/* Constantes dos elementos da interface. */
#define ALTURABOTAO 30
#define LARGURAINTERFACE 400
#define ALTURAINTERFACE 860
#define LARGURAJANELAHISTOGRAMA 512
#define ALTURAJANELAHISTOGRAMA 512
#define PULO_CORES 1
#define PULO_CONTRASTE 0.1
#define PULO_BRILHO 0.5
#define PULO_PESOKERNEL 0.0625
#define PULO_ZOOM 1

#define X_INTERFACE 1350	/* Constantes das coordenadas das janelas. */
#define Y_INTERFACE 100
#define X_KERNEL 1350
#define Y_KERNEL 650

#define X_ORIGINAL 200	
#define Y_ORIGINAL 200
#define X_NOVA 820
#define Y_NOVA 200

#define X_NAOEQUALIZADO 100
#define Y_NAOEQUALIZADO 30
#define X_EQUALIZADO 750
#define Y_EQUALIZADO 30

#define FORMATOIMAGEMSAIDA ".jpg"

#endif